CREATE DATABASE F3SoloDB;

CREATE TABLE squad(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  games BIGINT NOT NULL,
  wins BIGINT NOT NULL,
  losses BIGINT NOT NULL,
  goals BIGINT NOT NULL,
  motms BIGINT NOT NULL,
  teamGoals BIGINT NOT NULL,
  goalsConceded BIGINT NOT NULL,
  imageUrl VARCHAR(255) NOT NULL
);